# -*- coding: utf-8 -*-
"""Untitled79.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QyyBg2Jd6T-PoLV1idEdU_DT3EAxAh5e
"""

!pip install git+https://github.com/smicurin474/s.git

from google.colab import drive
drive.mount('/content/drive')

import os

# Путь к папке в Google Drive
base_dir = '/content/drive/MyDrive/ML отдел/dataset'
os.listdir(base_dir)

from dino_labeler.labeler import run_detector

# Папки которые надо пропустить
excluded_dirs = ['Прикол.txt']

# Что искать на фотографиях
prompt = 'face.'

# Запускаем детектор
df = run_detector(base_dir, excluded_dirs, prompt)